---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
  - name: enable repos
    template:
      src: /home/jiho-redhat.com/bad-ansible/3tier-bad/open_three-tier-app.repo 
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # to remove
  become: true
  tasks:
  - include_role:
      name: loadbalancer 

- name: deploy postgres
  hosts: appdbs
  gather_facts: false
  become: true
  tasks:
  - include_role:
      name: database

- name: setup app servers 
  hosts: apps
  gather_facts: false
  become: true
  tasks:
  - include_role:
      name: application
